dist: xenial
sudo: false

branches:
  only:
    - master

before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mkdir -p ~/.aws
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

script: 
  - terraform --version
  - aws iam get-user