dist: xenial

addons:
  snaps:
    - name: hugo
    - name: aws-cli
      classic: true
      channel: latest/edge

branches:
  only:
    - master
    - toha_website

before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mkdir -p ~/.aws
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

before_script:
  - which aws
  - ls -lah /snap/aws-cli/161/bin/
  - ./terraform/aws_envs.sh

script:
  - terraform --version
  - hugo

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh


after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"