name: auto-deploy-website
on:
  push:
    branches:
      - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install hugo
      - run: sudo apt-get install -y awscli
      - run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - run: sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - run: sudo apt install terraform=0.13.0
      - run: hugo
      - run: terraform version
      - name: setting up env and deploying
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash deploy.sh
