name: auto-deploy-website
on:
  push:
    branches:
      - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install hugo
      - run: sudo apt-get install -y awscli unzip
      - run: wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip
      - run: unzip /tmp/terraform.zip -d /tmp/terraform
      - run: sudo mv /tmp/terraform /usr/local/bin/terraform
      - run: chmod +x /usr/local/bin/terraform
      - run: hugo
      - run: terraform version
      - name: setting up env and deploying
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash deploy.sh
