name: build-hugo-website
on:
  pull_request:
    branches:
      - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install hugo
      - run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - run: sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - run: sudo apt install terraform=0.13.0
      - run: hugo
      - run: terraform version